### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "asdlja@sasd.com",
  "password": "asdasda"
}

### Sign in a user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "asdlja@sasd.com",
  "password": "asdasda"
}

### Find a particular user with a given id
GET http://localhost:3000/auth/2

### Find all user with a given email
GET http://localhost:3000/auth?email=cccc@cccc.com

### Delete user with a given id
DELETE http://localhost:3000/auth/1212312

### Update a user email with a given id
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "aaaa@aaaa.com"
}

### Update a user password with a given id
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "password": "bbbbbb"
}

### Update a user password & email with a given id
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "cccc@cccc.com",
  "password": "cccccc"
}